
import "@css/aos.css";
import "@css/bootstrap.min.css";
import "@css/flaticon.min.css";
import "@css/fontawesome-5.14.0.min.css";
import "@css/magnific-popup.min.css";
import "@css/nice-select.min.css";
import "@css/slick.min.css";
import "@css/style.css";
import "./globals.css";


export const metadata = {
  title: "Rathisoft Innovation",
  description: "Generated by Rathisoft Innovation",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/assets/images/logos/favicon1.png" />
      </head>
      <body className="dark-version">{children}</body>
    </html>
  );
}
